spring.application.name=pos_sys

spring.datasource.url=jdbc:mysql://localhost:3308/db_2_5
spring.datasource.username=root
spring.datasource.password=rootpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT config (secret must be >= 32 bytes, base64-encoded)
jwt.secret=RTy2xPH7PXtfH+eaiY2wH7FdYtJQhvqnRQkfdmo2rt8gi1kiD7l3e/LbSS1XWu5l
jwt.expiration=86400000